### ISSUE TITLE
^Lab do not count in Research Tree?

### ISSUE THREAD

**Issue by Norion1800** [Taludas/Anno2205-NewFrontiers#11]
I finally got to the Mars !  Great Cinematics :)

Now i build the research modules, but it seems like they do not count to the Tech Tree.
For example, i build 3 Heavy Industry Research Labs but i still have 0 in the Teach Tree and cannot research the skills.
Is that intended?

**Comment by Taludas** [comment]
Glad you reached the Red Planet and liked the atmosphere there!

You do not get workshop permits from building laboratories directly, but from building population on Mars. Please follow the questline, after some initial explanations you will get the "AI research colony" questline which asks you to build up Synths in steps of 5k. After each step you get a new workshop permit along with some of the other modules.
