### ISSUE TITLE
No Bonus on Shares intended?

### ISSUE THREAD

**Issue by Norion1800** [Taludas/Anno2205-NewFrontiers#13]
Hey. Still on my road to the biggest population with this mod :).

When i bought all shares of Saayman i noticed that the all share Produktion buff is 0%. 
Is that intended?

![screenshot_2024-05-30-18-29-58](https://github.com/Taludas/Anno2205-NewFrontiers/assets/148073801/6f1441ec-fd63-46f3-a464-8b27cdb403cc)

**Comment by Taludas** [comment]
I guess it is a "feature" of the vanilla game on veteran difficulty. I haven't changed anything in this regard.

**Comment by Norion1800** [comment]
I loaded an old save on veteran here without the mod.
Not only is the full share bonus there with 10% but also the normal share bonus is 3 times higher.
![Uploading screenshot_2024-05-30-23-36-01.png…]()

**Comment by Taludas** [comment]
Have you checked whether this is only a display bug within your current corporation? So if the percentage values on the buildings differ from the ones displayed in the stock market.

Also, you could have changed the setting for stock market difficulty in this specific corporation to easy - that would give the 3% per share plus 10% bonus as seen in the picture - while still being a veteran difficulty corporation?

Again, I have not changed any values concerning the stock market! Please recheck with a wiki site or some other source what the actual effects are per difficulty setting.

**Comment by Norion1800** [comment]
Ah.  That explains it.  Sorry for the trouble and thank you for explaining it.
