### ISSUE TITLE
Nachträglich Katastrophen ausschalten?

### ISSUE THREAD

**Issue by Thorblerone** [Taludas/Anno2205-NewFrontiers#15]
Folgendes Problem: Ich habe jetzt den Mars freigeschaltet (danke für die extrem schnelle Antwort), aber jetzt bin ich im Frühling und durch die starken Stürme kann ich nicht auf dem Mars anfange, da Androiden nicht durch das globale Lager gedeckt sind. (Bauroboter schon). Gibt es eine Möglichkeit, das Wetter noch auszuschalten oder das zu umgehen?

**Comment by Taludas** [comment]
Ich frage mich, warum bei so vielen die Jahreszeit im Frühling anfangen zu scheint?
Die Startjahreszeit auf dem Mars sollte immer der Sommer sein. Solltest du so lange gewartet haben mkt der Besiedlung, dass bereits Frühling ist, musst du einfach nur warten, bis die Jahreszeit wieder wechselt (siehe Quest Timer an der entsprechenden Quest im seitlichen Quest Tracker!)
Ansonsten bitte genauere Details zu Starteinstellungen bei Katastrophen und Auftragsdauer und ein Screenshot der aktuell aktive Jahreszeiten Quest.

**Comment by Thorblerone** [comment]
![Screenshot (41)](https://github.com/Taludas/Anno2205-NewFrontiers/assets/171348164/ce741f66-b3bc-4de9-934f-0edd2938ff23)

Die Starteinstellungen sind bei mir alle auf der einfachsten Stufe, bis auf die Katastrophen die sind auf selten eingestellt und Auftragszeit ist auf Kein Limit. Aber 60 Stunden scheinen mir da schon etwas viel, und bin cirka nach 17 Spielstunden auf dem Mars angekommen.

**Comment by Taludas** [comment]
Du hast dich leider nicht an die Installationsanleitung gehalten. Es ist nun so, dass dir Quest für den Sommer nicht abläuft durch das fehlende Auftragslimit. Durch die eingeschalteten Katastrophen bekommst du allerdings trotzdem den Effekt ab (auch wenn es jetzt der falsche ist, warum auch immer, denn das Skript startet beim ersten Betreten des Mars immer den Sommer Effekt). Der Effekt wird nun auch nach der angegebenen Zeit auslaufen. Du hast also die maximal ungünstigste Kombination an Einstellungen gewählt. Wäre beides auf aus bzw. kein Limit, dann hättest du den Sommer ewig und keinen Effekt. Also entweder beides auf an oder beides aus fürs nächste Mal.
Jetzt hilft dir nur noch die Konsole. Am besten stellen wir den Effekt für diesen Spielstand jetzt komplett ab.
Dazu
1. Shift+F1 drücken, um die Konsole zu öffnen.
2. Eingeben (ohne jeglichen Tippfehler, auf Groß-und Kleinschreibung achten!):
debug.startSectorEffect(19990374,19990093)
3. Enter drücken
4. Shift+F1 drücken, um die Konsole zu schließen.
5. Der Sektor Effekt sollte weg sein.
