### ISSUE TITLE
[Rechtschreibung] Drohne

### ISSUE THREAD

**Issue by FrlPetronella** [Taludas/Anno2205-NewFrontiers#18]
Drohne schreibt sich mit h in der Mitte. Im Spiel fehlt es.

![2024-06-07](https://github.com/Taludas/Anno2205-NewFrontiers/assets/166033711/d928d837-801c-45d6-a2e0-573b4041b301)

**Comment by Taludas** [comment]
Wird im nächsten Patch behoben 👍🏻

**Comment by Taludas** [comment]
fixed in 3be29576fc2d8386652e7bf12d47c5bbcbf3f946
