### ISSUE TITLE
No Nutrient Powder Production

### ISSUE THREAD

**Issue by Proudusamember** [Taludas/Anno2205-NewFrontiers#2]
The production building for Nutrient Powder is not showing up in the game. This is stalling my ability to make juice, and I can no longer progress. I downloaded and copied over v1.0.0.2 and still no production buildings showed up.

**Comment by Taludas** [comment]
Most likely the mod hasn't loaded correctly. Do you see the Mars planet in the strategic overview (world map)? If no, you probably have missed to enable loading local files as it is discribed in points 5-7 in the installation instruction.

**Comment by Proudusamember** [comment]
I do see the Mars planet in the Strategic overview. I also verified the config file does say True.

**Comment by Taludas** [comment]
Can you show me a screenshot of your Operators build menu please? You could still have old mod files active without knowing...

**Comment by Taludas** [comment]
Can't reproduce, author not answering, probably an issue with installing the mod.

**Comment by Domnc84** [comment]
I have the same issue, 
please finde attached some screenshots
![Screenshot 2024-05-29 230325](https://github.com/Taludas/Anno2205-NewFrontiers/assets/171191828/0234f6f3-c920-4021-ac8a-9bbc0dc50403)

**Comment by Domnc84** [comment]
![image](https://github.com/Taludas/Anno2205-NewFrontiers/assets/171191828/af756e20-2b06-43d2-990e-21007c42ebbf)

**Comment by Taludas** [comment]
Did you start a new savegame for the mod? Otherwise the unlock triggers for the new buildings won't work!

**Comment by Domnc84** [comment]
It was a new savegame

**Comment by Taludas** [comment]
Then I don't have any idea what happens there. Reinstall the mod by first deleting the data folder, and then download the newest version again and install the data folder as usual. Start a new save and hope for the best.

**Comment by Domnc84** [comment]
Ok, after the 4th reinstallation it works, 
I only made one change to the download, the last time I used the “Download now” button on your site and not the download in your installation instructions

**Comment by Taludas** [comment]
Ah, that could be it, if you used the installation instructions on GitHub there was a very old link in it to a Google drive folder with the beta version inside. Nevertheless that already had the Nutrient Powder and everything else, so not exactly sure why it happens. Anyways, I fixed the download link and all should be good now.
