### ISSUE TITLE
Balancing Sektoreigenschaft "Schiefergebiet" unausgewogen

### ISSUE THREAD

**Issue by FrlPetronella** [Taludas/Anno2205-NewFrontiers#20]
"Schiefergebiet" heißt +30% Produktivität für Weingüter und +50% Stromverbrauch bei Minen. Meiner Ansicht nach stehen Vor- und Nachteil in keinem sinnvollen Verhältnis zueinander.

Am Anfang macht sich das nicht so bemerkbar, vor allem um Walbruck-Becken mit dem Damm-Projekt. Aber so langsam muss ich Produktion in andere Sektoren umlagern, weil der Strom nicht mehr für die Häuser reicht. Das wiederum führt zu einem Verlust an Urbanisierung.

Ich upgrade jetzt auf Investoren. Da auch die Häuser Strom verbrauchen, muss ich gefühlt alle 5 Häuser ein Solarkraftwerk bauen. Die Landschaft ist schon voll davon.

Nach meiner Einschätzung führt das früher oder später dazu, dass die Minen in dem Sektor nicht oder erst im Lategame genutzt werden können. Das scheint mir nicht der Sinn der Übung zu sein.

**Comment by Taludas** [comment]
Erstmal allgemein bezüglich der Sektorenprojekte: Sie dienen definitiv der Spezialisierung eines Sektors. Ein Sektor mit dem Trait ist definitiv eine mid game tech, sodass man dort weniger Wein bauen muss. Im Gegenzug muss man mehr Energiemodule an die Minen bauen und eventuell energieintensive Minen (v.a. Silicium) in andere Sektoren auslagern.

Im Lategame wird der Effekt definitiv unbalanced, da du viel mehr Wein auf dem Mond anbauen kannst und alle Minenbauplätze definitiv brauchst.

Ich würde vorschlagen, den Debuff etwas abzuschwächen, ich weiß ehrlicherweise nicht, ob ich den Effekt 1:1 von Annothek oder dem Vanilla Spiel übernommen habe, selber geschrieben habe ich ihn nicht. Ich denke eine Reduktion auf -15% könnte man erwägen, ähnlich wie es bei den anderen Effekten ist (ein Wert 30 und der andere 15)

**Comment by Taludas** [comment]
fixed in c6609434a4251a3725b1f45bad1550ba0c0725b4
