### ISSUE TITLE
Wenn man auf Mars auf die Bevölkerungs Sicht(Button ganz unten rechts) geht, stürtzt das Spiel ab

### ISSUE THREAD

**Issue by NeoEx0** [Taludas/Anno2205-NewFrontiers#22]
Wenn man auf dem Mars auf die Bevölkerungs Sicht(Button ganz unten rechts) geht, stürtzt das Spiel ab

V1.06

**Comment by Taludas** [comment]
Danke für die Info, ist aber bereits auf der Known issues Liste enthalten. Ich weiß leider auch nicht warum es passiert geschweige denn einen Weg das zu fixen, daher bleibt es vorerst was es ist, ein ungelöstes Known issue.
