### ISSUE TITLE
[Balancing] Stromverbrauch der EW nicht kalkulierbar

### ISSUE THREAD

**Issue by FrlPetronella** [Taludas/Anno2205-NewFrontiers#23]
Der Stromverbrauch der EW in der gemäßigten steigt mit jeder Bevölkerungsstufe. Ich habe erst vergleichsweise wenige EW (Firma Level 39), aber der Stromverbrauch ist gigantisch. Er scheint mit jedem Heraufstufen des Gebäudes exponentiell anzuwachsen. Allerdings ist der Verbrauch nicht kalkulierbar, da es keine Anzeige gibt, wie viel Strom ein Gebäude auf welcher Bevölkerungsstufe verbraucht.

Anbei die Siedlungen im Walbruck-Becken. Die paar Hütten verbrauchen fast 7000 Einheiten Strom. Das ist deutlich zu viel meiner Meinung nach. Der große Überschuss an Strom kommt daher, dass ich den EW den Strom abgedreht habe. Wenn ich ihn einschalte, bin ich mit ca. 1800 im Minus. Das muss ich jetzt erst mal heranschaffen.

Das Problem dahinter ist, dass man durch die komplexeren Produktionsketten viel mehr Betriebe insgesamt braucht, wodurch auch die Produktion der Bedarfsgüter schon deutlich mehr Strom benötigt. Dann kommen noch solche Gebäude wie das Infodrom in der Tundra mit 500 Strom dazu.

Gibt es zumindest eine Möglichkeit, den Bedarf an Strom im Voraus zu berechnen? Also z. B. so:

1 großes Arbeiterhaus benötigt x Einheiten Strom/min.
Upgrade auf Administratoren erhöht den Stromverbrauch um y Einheiten oder y Prozent.

Dann könnte man sich vorher ausrechnen, wenn ich 3 Häuser upgrade, muss ich vorher soundsoviel Strom bereitstellen.

![screenshot_2024-06-23-21-41-43](https://github.com/Taludas/Anno2205-NewFrontiers/assets/166033711/fa96eabb-5b32-4d0d-84e7-5eb2700563d4)
![screenshot_2024-06-23-21-41-35](https://github.com/Taludas/Anno2205-NewFrontiers/assets/166033711/eb6d19a3-91d0-417f-bf97-0d4b5854e5ff)

**Comment by Taludas** [comment]
Hi, du beobachtest genau richtig. Der Stromverbrauch steigt mit jeder Stufe an, da auch die maximale Einwohnerzahl pro Haus mit Faktor 5 zunimmt als auch der Stromverbrauch um Faktor 2. Es ist auch definitiv gewollt, dass Strom im Endgame zu einem Problem wird. Nicht umsonst heißt es ja in der Story, dass die Energiekrise der Erde gelöst werden muss.

Dafür bietet die Mod einige Möglichkeiten an, um gegenzusteuern:
1. Die Akkumulatoren-Module an Energiegebäuden. Durch das Bauen der Energiemodule an Energiegebäuden lässt sich deren Output um 50% bzw. 75% mit den besseren Modulen anheben. Beachte hierbei, dass dieser Buff multiplikativ mit anderen Buffs aus dem Nexus ist.
2. Im Nexus gibt es die Energietechnologien, die sowohl Verbrauch von Produktionen als auch Erzeugung in Energieanlagen erhöhen. Diese sollten auf jeden Fall genutzt werden. Besonders die Technologien "Sommerzeit" auf Stufe 4 außen und "Kinetische Mikrogeneratoren" auf Stufe 5 sind im späten Spiel Pflicht, um den Energieverbrauch durch Wohnhäuser zu reduzieren.
3. Synthetiks verbrauchen im Vergleich zu Investoren deutlich weniger Energie pro Einwohner.
4. Energiehungrige Produktionsgebäude können und sollten mit den Akkumulator-Modulen ausgestattet werden. 
5. Solaranlagen können in die Stadt eingeplant werden und verbrauchen recht wenig Platz bei gutem Preis-Leistungsverhältnis. Durch Umstrukturieren im Spiel und im Nexus können sogar die Gezeitenkraftwerke auf den Küstenbauplätzen wieder relevant werden.
6. Auf dem Mars soll sich auch einiges an Energie durch Wind- und Solarenergie gewinnen lassen, je nach Bau-/Spielstil.

Ich habe schon von anderen Spielern mit deutlich größeren Spielständen gehört, dass das mit der Energie klappt, die Anzahl an notwendigen Fusionsreaktoren dennoch erwartungsgemäß in die Höhe geschossen ist, was für mich aber absolut akzeptabel ist. Ich würde sagen, ich habe definitiv das Ziel erreicht, dass sich der Spieler auch nach Errichten der ersten Fusionskraftwerke noch mit dem Thema Energie beschäftigen muss, was im Originalspiel nicht wirklich der Fall war.

Bezüglich deiner Frage nach dem Verbrauch: Ich konnte noch immer nicht nachvollziehen, wie genau sich der Verbrauch aus den Werten in der population_balancing.xml berechnet.
Dennoch kann man einfach ausprobieren, wie viel Energie man benötigt:
5 Arbeiterkomplexe: 1 Energie
1 Administratorenkomplex: 2 Energie
1 Managerkomplex: 18 Energie
1 Investorenkomplex 176 Energie
1 Synthetikkomplex 195 Energie

So weit zumindest meine Testungen, für die Hauptkomplexe also wie oben angegeben ungefähr Faktor 10 pro Stufe, Synths dann etwas moderater. Dafür brauchen die deutlich mehr Waren und zahlen keine Steuern.

Wir können jetzt ewig weiter über Balancing diskutieren, aber wir werden ohne die genauen Formeln von Ubi zu kennen und ohne richtige Playtests mit mehreren Spielergruppen  (wo die Leute tatsächlich auch Feedback geben)  für niemanden eine 100% zufriedenstellende Lösung finden können. Mein Fokus ist auf jeden Fall ein mechanistisch anspruchsvolles Gameplay zu bieten, was sich definitiv mehr Richtung Rekordbau orientiert und nicht Richtung casual Spieler. Das ist meiner Meinung nach durch die oben genannten verschiedenen Gameplay-Mechanismen, um dieses Problem anzugehen, gegeben.

**Comment by Taludas** [comment]
Du musst bedenken, dass du mit dem Mars am Ende ALLE Technologien nutzen kannst. Bis dahin finde ich die Challenge, die Energie herbeizuschaffen durchaus gerechtfertigt.
