### ISSUE TITLE
Unable to start Mars mission

### ISSUE THREAD

**Issue by Soundemotion** [Taludas/Anno2205-NewFrontiers#24]
I have reached every milestone, but i cannot start the mars mision... 
See the picture...
![screenshot_2024-06-28-22-41-31](https://github.com/Taludas/Anno2205-NewFrontiers/assets/174150647/a6933f56-6cb1-479b-a7cf-13ef42d7a3ee)

**Comment by Taludas** [comment]
Du spielst (vermutlich) nicht auf der aktuellsten Version. Die Questbeschreibung ist mittlerweile aktualisiert und spezifiziert den Sektor, in dem die Marsstartrampe gebaut werden soll. 
Dies muss zwingend im ERSTEN Mondsektor erfolgen (auch wenn da sin den älteren Versionen nicht so in der Questbeschreibung steht).
Da deine Permits jetzt verbraucht sind,usst du die Quest mit der Konsole lösen:
1. Die Quest an der Seite im Questtracker selektieren, sodass die Details angezeigt werden (aktive Quest)

2. Shift+F1 drücken. Die Konsole öffnet sich.

3. Eingeben (Achtung, Groß- und Kleinschreibung beachten und keine Rechtschreibfehler machen, sonst friert das Spiel ein)

quests.reachSelectedQuest()

4. Enter drücken. Die Quest sollte abgeschlossen sein und das Introvideo vom Mars startet.

5. Shift+F1 nochmal drücken, um die Konsole wieder zu schließen.

Viel Erfolg

**Comment by Soundemotion** [comment]
Danke!
