### ISSUE TITLE
Link zur deutschen readme fehlt

### ISSUE THREAD

**Issue by FrlPetronella** [Taludas/Anno2205-NewFrontiers#25]
Auf der Startseite sind zwei Links, die zur englischen bzw. deutschen Doku führen sollen. Der Link für die deutsche Version führt aber auch zur englischen readme.md.

Ist mir schon vor längerem aufgefallen, aber ich hab mich erst jetzt aufgerafft, das hier niederzuschreiben. sorry.

Gruß Petronella

**Comment by Taludas** [comment]
Danke für den Hinweis, habe es entsprechend korrigiert!
