### ISSUE TITLE
Ausbildungszentren produzieren 0 Astronauten pro Minute

### ISSUE THREAD

**Issue by SunnyM00n** [Taludas/Anno2205-NewFrontiers#26]
Mir ist aufgefallen, dass Ausbildungszentren 0 Astronauten produzieren, soll das so sein oder ist das ein Bug?

Habe es mit einer kompletten Neuinstallation von Spiel und Mod versucht (mit einem frischen Download von Github)
Tritt auch in einem komplett neuen Savegame auf

 ![screenshot_2024-07-05-00-27-10](https://github.com/Taludas/Anno2205-NewFrontiers/assets/49319803/0e7a2a6d-2ef7-4e84-9544-c9638573ad4a)

**Comment by Taludas** [comment]
Hi, das ist ein Known Issue. Es liegt begründet in der Änderung des UIs der Ausbildungszentren, damit sie die Zusatzwaren anzeigen können, die mit der Stufe 5 Forschung der Schwerindustrie dazukommen. Es ist nur ein visueller Fehler, denn die tatsächliche Anzahl an generierten Astronauten ist nach wie vor 25 bei 100%iger Auslastung und kann als kumulierter Wert der Session über das "Versorgungsflug" UI eingesehen werden, dass nach dem Bau des ersten Ausbildungszentrums links neben dem Kontostand angezeigt wird. Daher working-as-intended, auch wenn es unschön ist, aber das ist leider eine Grenze der Modbarkeit des Spiels.
Ich werde den Punkt einmal mit aufnehmen in die offizielle Known Issues Liste, damit andere User auch bescheid wissen, denn dort fehlt es noch. In sofern danke ich für den Hinweis!
