### ISSUE TITLE
Sackgasse bei Projekt 31, keine Raketentriebwerke mehr verfügbar

### ISSUE THREAD

**Issue by FrlPetronella** [Taludas/Anno2205-NewFrontiers#27]
Ich bin offenbar in einer Sackgasse gelandet, weil ich einen der Raumhäfen auf dem Mond bereits zur Marsstartrampe ausgebaut habe, lange bevor diese Aufgabe kommt.

In der englischen Readme steht "31. The Second Mars Mission": Settle 10000 Geniuses and upgrade your Transmission Spaceport in one of your Moon sectors with a Mars Launcher."  Tatsächlich soll ich aber 5 Raketentriebwerke besitzen. s. Screenshot. Die sind aber offenbar beim Upgrade des Raumhafens verbraten worden. 

Was nun?
![screenshot_2024-07-27-20-01-20](https://github.com/user-attachments/assets/250f6e67-7bbb-4ce8-a102-290466347975)

**Comment by Taludas** [comment]
Hi, sorry für die späte Antwort:
Die Quest war vermutlich schon gestartet, bevor die v1.0.9 installiert wurde. Daher hast du noch die alte Questbeschreibung. Die Questbeschreibung ist mittlerweile aktualisiert und spezifiziert den Sektor, in dem die Marsstartrampe gebaut werden soll.
Dies muss zwingend im ERSTEN Mondsektor erfolgen (auch wenn da sin den älteren Versionen nicht so in der Questbeschreibung steht).
Da deine Permits jetzt verbraucht sind und du auch keine weiteren bekommen kannst, musst du die Quest mit der Konsole lösen:

Die Quest an der Seite im Questtracker selektieren, sodass die Details angezeigt werden (aktive Quest)

Shift+F1 drücken. Die Konsole öffnet sich.

Eingeben (Achtung, Groß- und Kleinschreibung beachten und keine Rechtschreibfehler machen, sonst friert das Spiel ein)

quests.reachSelectedQuest()

Enter drücken. Die Quest sollte abgeschlossen sein und das Introvideo vom Mars startet.

Shift+F1 nochmal drücken, um die Konsole wieder zu schließen.

Viel Erfolg

**Comment by Taludas** [comment]
Edit: Habe nochmal geguckt, tatsächlich ist die Questbeschreibung in der deutschen Variante noch nicht angepasst. Kommt daher noch mal auf die Liste.

**Comment by Taludas** [comment]
Fixed in 93cf82de94427261c55a1b7a0fe01996cd507d13

**Comment by FrlPetronella** [comment]
Danke. Har funktioniert.
