### ISSUE TITLE
Übernahme Marssektor, Rechtschreibfehler 

### ISSUE THREAD

**Issue by FrlPetronella** [Taludas/Anno2205-NewFrontiers#28]
Kaum habe ich den Mars freigeschaltet, bin ich schon wieder hier. ;)

Auf dem Bildschirm für die Übernahme des Marssektors ist ein Rechtschreibfehler:

Adnroiden statt Androiden

![2024-08-11](https://github.com/user-attachments/assets/b3c81fe0-d4c9-411e-bd07-d75d6eb20069)

**Comment by Taludas** [comment]
- gefixt in 8c27e48c089e0423c7a29c1a5bd9e1f9bce49b5f
