### ISSUE TITLE
Mars, Aufgabe 32, Mengenangabe fehlt

### ISSUE THREAD

**Issue by FrlPetronella** [Taludas/Anno2205-NewFrontiers#29]
Ich soll Titanplatten und Baubots einlagern, aber es fehlt die Mengenangabe. Oder reicht jeweils eine Einheit?

![2024-08-11 (1)](https://github.com/user-attachments/assets/24c1c4bc-9547-4cd9-aa30-62685b756ee9)

**Comment by Taludas** [comment]
Es reicht eine Tonne. Geht einfach nur darum anzuzeigen, dass man die Baumaterialien lokal produzieren kann.
