### ISSUE TITLE
debug.toggleSectorEffect Crashes game

### ISSUE THREAD

**Issue by onebadassclown** [Taludas/Anno2205-NewFrontiers#3]
while attempting to correct the weather on the moon i used the debug.toggleSectorEffect found under known issues to do so. It crashed the game every time, I've tried different things but it seems even just typing deubg.toggle crashes it.

**Comment by Taludas** [comment]
The console is not tolerant to typos or spelling errors with the capitalisation. It crashes the game. Therefore it is very important to follow my given example. Unfortunately the console doesn't allow for easy copy and paste...
