### ISSUE TITLE
Marsianischer Titantagebau, Beschreibung im Baumenü falsch

### ISSUE THREAD

**Issue by FrlPetronella** [Taludas/Anno2205-NewFrontiers#30]
Klickt man im Baumenü den Marsianischen Titantagebau an, steht in der Beschreibung "Liefert Kobalt zur Weiterverarbeitung." Copy&Paste-Fehler, schätze ich.

![2024-08-11 (2)](https://github.com/user-attachments/assets/4a71c79c-13ce-40b8-93c0-71606729afa0)

**Comment by Taludas** [comment]
- gefixt in 5a4acad6179e41c505d314eef64c519a3761b43b
