### ISSUE TITLE
Mars-Herbst hat keine erkennbare Auswirkung

### ISSUE THREAD

**Issue by FrlPetronella** [Taludas/Anno2205-NewFrontiers#31]
Ich hatte jetzt erstmals dem Mars-Herbst. Dabei sollen alle "Bergwerksbauplätze" geschlossen sein. Das klingt für mich so, als ob alle Produktionen an Bergbauplätzen, egal ob Strom oder Bodenschätze, den Betrieb einstellen sollten.

Tatsächlich hatte der Mars-Herbst aber keine erkennbaren Auswirkungen. Alle Bergwerke und Windkraftwerke produzierten munter weiter.

Habe ich die Beschreibung falsch interpretiert?

**Comment by Taludas** [comment]
Ich habe dieses Problem auch bei einem anderen Spieler beobachten können. In seinem Video hat der "erste" Herbst auch keinen Effekt gehabt. Erkennbar ist das immer sehr gut daran, dass das kleine rote Symbol neben dem Sektoren-Icon auf der Weltkarte fehlt. Nach einem Zyklus hat sich das ganze dann aber auch wieder eingerenkt. In einem Stream eines anderen Spielers, konnte ich dieses Verhalten nicht bestätigen. Wenn man sich den Code anschaut, ergibt sich für mich auch nicht, warum das ganze passiert, und vor allem dann nur beim ersten Wechsel von Sommer auf Herbst.

Die Jahreszeiten sind und bleiben ein nicht optimales System, bei dem sehr viel Spielraum für Fehler ist. Das ganze war so niemals vom Spiel vorgesehen und ist daher entsprechend fehlerbehaftet.

Ich habe das Problem in den Known Issues sehr generell beschrieben, und die Anleitung zur Nutzung der Konsole mit dazugesetzt, sodass man im Fall der Fälle manuell nachhelfen kann. https://taludas.github.io/#/de/Anno2205/KnownIssues -> Vorletzter Spiegelstrich.
