### ISSUE TITLE
Marssektor, Klick auf Einwohner-Upgrade-Menü lässt Spiel abstürzen

### ISSUE THREAD

**Issue by FrlPetronella** [Taludas/Anno2205-NewFrontiers#32]
Ich habe im Marssektor auf das Einwohner-Menüp rechts unten geklickt, um zu sehen, wie viele Häuser ich habe. Das Spiel fror daraufhin ein. Es ließ sich auch nicht über Rechtsklick->Fenster schließen beenden. Es blockierte den Desktop so, dass auch der Taskmanager nicht nach vorn kam. Ich musste den Rechner rebooten.

Kann sein, dass man das Menü nicht aufmachen sollte, weil man auf dem Mars einen Einwohnertyp hat, den es im Spiel sonst nicht gibt. Das wäre aus meiner Sicht nicht schlimm, sollte dann aber dokumentiert sein.

**Comment by Taludas** [comment]
Das beschriebene Problem ist in den Known Issues unter dem Punkt "Mars" beschrieben (Sechster Spiegelstrich): 
"Die Verwendung des Gebäude-Filter-Reiters neben der Minimap (die Bevölkerungs-Schaltfläche) in der Mars- Session führt zu einem Einfrieren des Spiels, das nur durch Beenden der Task behoben werden kann."

Bei mir konnte ich das Spiel in dem Fall allerdings mithilfe des Task-Managers beenden und musste nicht den Rechner rebooten.
