### ISSUE TITLE
No Orbit Session

### ISSUE THREAD

**Issue by Norion1800** [Taludas/Anno2205-NewFrontiers#4]
I cannot see the Orbit Session. 
I build Training Centers in the Thundra and normal Session and the do send the Shuttels, but on the World Map there is no Orbit Session.
Also got the Quest from ADAM to open it.
The only thing i can think off that might have impacted it, is that i unlocked the Orbit before i entered the moon seesion. 
Though after entering the moon it was still not there :(
Is it because of the mod or just the base game?

**Comment by Taludas** [comment]
I have fixed it in https://github.com/Taludas/Anno2205-NewFrontiers/commit/83b742440d78e9bd617013db5ce8b953e314b39e
This however takes effect only in a new savegame. For your started savegame you need to reach the Tier 2 Moon spaceport (first upgrade) to unlock it. Sorry for the inconvenience.
