### ISSUE TITLE
Mod setzt Club-Belohnungen außer Kraft

### ISSUE THREAD

**Issue by FrlPetronella** [Taludas/Anno2205-NewFrontiers#5]
Wenn man die Modifikation aktiviert, sind die UBI-Club-Belohnungen, wie die Firmenlogos der Eden Initiative und Global Trust sowie die Segelfarben des Kommandoschiffs, nicht mehr verfügbar. 

Deaktiviert man die Mod wieder, sind auch die Club-Belohnungen wieder da. Ist kein Beinbruch, sollte aber dokumentiert werden. 

Edit: Nachdem ich die Modifikation erneut aktiviert hatte, blieben die Club-Belohnungen verfügbar.

**Comment by Taludas** [comment]
Hatte das auch ausprobiert, und bei mir keine Einschränkungen dahingehend festgestellt, die Logos funktionierten weiterhin wunderbar und auch die Seltenen Ressourcen könnte man sich abholen. Daher schließe ich es erst mal und gucke, ob noch jemand das Problem hat.

**Comment by FrlPetronella** [comment]
![2024-05-27 (1)](https://github.com/Taludas/Anno2205-NewFrontiers/assets/166033711/160e715e-9077-47dd-95e0-9e851f46be81)
![2024-05-27](https://github.com/Taludas/Anno2205-NewFrontiers/assets/166033711/94a7a628-aba8-4bbe-9d3d-8f60eb16543a)

Hier Screenshots. Als ich das Spiel heute gestartet habe, waren die Club-Belohnungen wieder deaktiviert. Selbes Spiel wieder: Mod deaktivieren. Spiel starten. Alles wieder gut. Spiel beenden, Mod wieder aktivieren, immer noch gut. Mal sehen, was beim nächsten Mal ist, komme aber die kommenden Tage nicht dazu, weiterzuspielen.
