### ISSUE TITLE
moon

### ISSUE THREAD

**Issue by mimistrz** [Taludas/Anno2205-NewFrontiers#7]
hello, a new disaster has appeared on the moon and the counter lasts for 60 hours, is this correct? xD 
![obraz](https://github.com/Taludas/Anno2205-NewFrontiers/assets/170891697/a50cda1b-eb5d-45a0-981b-ea3ab0dd6e5d)

**Comment by Taludas** [comment]
Known Issues: last point:
Sometimes, Martian Season effects can randomly start on the Moon. This is a problem, as they last for a very long time and cannot be resolved with a quest. Again, you need to use the console to get rid of them, if it happens to you: First, enter the Moon session in question. Now press Shift+F1 to open the console and type `debug.toggleSectorEffect(GUID)`. Proceed to replace the "GUID" placeholder with the corresponding GUID from the currently active season effect (see below). Press enter and close the console with Shift+F1 again. The effect should be gone.
  |Season|Summer|Autumn|Winter|Spring|
  |---|---|---|---|---|
  |GUID|19990307|19990378|19990370|19990374|
